language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t bonquyquy/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true bonquyquy/docket-react npm run test